In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import statsmodels.api as sm

from optbinning import OptimalBinning
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [2]:
# ── Config ────────────────────────────────────────────────────────────────────
FILE_PATH        = r"D:\KL-lieuvth2\kaggle\input\home-credit-default-risk\master_data.csv"
ID_COL           = "SK_ID_CURR"
TARGET_COL       = "TARGET"

MISSING_THR      = 0.20
INF_THR          = 0.20
IV_THR           = 0.01
IV_MAX           = 10
VIF_THR          = 5          # VIF threshold (replaces GVIF_THR)
CORR_THR         = 0.80
GINI_IMPROVE_THR = 0.005
TEST_SIZE        = 0.30
RANDOM_STATE     = 42
IV_BINS          = 10
EPS              = 1e-6

OUTPUT_CSV          = "master_data_train_test_split.csv"
FEATURE_SHORTLIST   = "feature_shortlist.csv"

## 1. Load data — Train/Test split & save CSV with flag_train_test

In [3]:
# df = pd.read_csv(FILE_PATH)
# df = df.drop(columns=[c for c in ["flag_train_val"] if c in df.columns])
# print("Shape after load:", df.shape)

In [4]:
# # ── Train / Test split right at Step 1 ────────────────────────────────────────
# train_idx, test_idx = train_test_split(
#     df.index,
#     test_size=TEST_SIZE,
#     random_state=RANDOM_STATE,
#     stratify=df[TARGET_COL],
# )

# df["flag_train_test"] = "test"
# df.loc[train_idx, "flag_train_test"] = "train"

# # Save full data with flag to CSV
# df.to_csv(OUTPUT_CSV, index=False)
# print(f"Saved: {OUTPUT_CSV}")
# print(f"Train: {(df['flag_train_test']=='train').sum():,}  |  Test: {(df['flag_train_test']=='test').sum():,}")
# print("Shape:", df.shape)

In [5]:
df = pd.read_csv(OUTPUT_CSV).iloc[:, 1:]

In [6]:
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,CC_BALANCE_DIFF1_MEAN,CC_BALANCE_DIFF2_MEAN,CC_BALANCE_DIFF3_MEAN,CC_BALANCE_DIFF6_MEAN,HAS_BUREAU_HISTORY,HAS_PREV_APPLICATION,HAS_POS_HISTORY,HAS_INSTALLMENT_HISTORY,HAS_CREDIT_CARD,flag_train_test
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,NaN,NaN,NaN,NaN,1,1,1,1,0,train
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,NaN,NaN,NaN,NaN,1,1,1,1,0,train
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,NaN,NaN,NaN,NaN,1,1,1,1,0,train
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0.0,0.0,0.0,NaN,0,1,1,1,1,test
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,NaN,NaN,NaN,NaN,1,1,1,1,0,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,NaN,NaN,NaN,NaN,0,1,1,1,0,test
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,NaN,NaN,NaN,NaN,0,1,1,1,0,train
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,NaN,NaN,NaN,NaN,1,1,1,1,0,train
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,NaN,NaN,NaN,NaN,1,1,1,1,0,train
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,NaN,NaN,NaN,NaN,1,1,1,1,0,train

In [7]:
# separate features, target
list_features = [col for col in df.columns if col not in ['TARGET','SK_ID_CURR']]
# features that starts with EXT_
# list_ext_features = [col for col in df.columns if col.startswith('EXT_')]
# list ethical features
list_ethical_features = [col for col in df.columns if 'GENDER' in col]
# list flag document features
list_document_features = [col for col in df.columns if 'FLAG_DOCUMENT' in col]

In [8]:
cols_to_drop = list(set(list_ethical_features + list_document_features))
df = df.drop(columns=cols_to_drop, errors='ignore')

In [9]:
print("Shape after dropping columns:", df.shape)

Shape after dropping columns: (307511, 238)

## 2. Drop high-missing & high-infinity features

In [10]:
# Work on df without the flag column
flag_col = df["flag_train_test"].copy()
df = df.drop(columns=["flag_train_test"])

# ============================================================
# Missing statistics
# ============================================================
miss_count = df.isna().sum()
miss_rate  = df.isna().mean()

missing_stats = pd.DataFrame({
    "missing_count": miss_count,
    "missing_rate": miss_rate
}).sort_values("missing_rate", ascending=False)

drop_missing = missing_stats.loc[
    missing_stats["missing_rate"] > MISSING_THR
].index.tolist()

df = df.drop(columns=drop_missing)


# ============================================================
# Infinity statistics
# ============================================================
num_cols = df.select_dtypes(include=np.number).columns

inf_count = np.isinf(df[num_cols]).sum()
inf_rate  = np.isinf(df[num_cols]).mean()

inf_stats = pd.DataFrame({
    "inf_count": inf_count,
    "inf_rate": inf_rate
}).sort_values("inf_rate", ascending=False)

drop_inf = inf_stats.loc[
    inf_stats["inf_rate"] > INF_THR
].index.tolist()

df = df.drop(columns=drop_inf)


# ============================================================
# Re-attach flag
# ============================================================
df["flag_train_test"] = flag_col


# ============================================================
# Summary
# ============================================================
print(f"Dropped missing : {len(drop_missing)}")
print(f"Dropped infinity: {len(drop_inf)}")
print(f"Remaining       : {df.shape[1] - 1}")
print("Shape:", df.shape)

print("\nTop missing features:")
print(missing_stats.head(10))

print("\nTop infinity features:")
print(inf_stats.head(10))

Dropped missing : 59
Dropped infinity: 0
Remaining       : 178
Shape: (307511, 179)

Top missing features:
                                    missing_count  missing_rate
CC_DRAWINGS_PAYMENT_DPD_CORR_MEAN          298365      0.970258
CC_UTIL_DPD_CORR_MEAN                      289701      0.942083
POS_PAID_DPD_CORR_MEAN                     270904      0.880957
CC_PAYMENT_TOTAL_TO_MIN_RATIO_MEAN         248232      0.807230
CC_DRAWINGS_PAYMENT_RATIO_MEAN             246824      0.802651
CC_UTIL_DIFF6_MEAN                         232661      0.756594
CC_BALANCE_DIFF6_MEAN                      230317      0.748972
CC_UTIL_DIFF3_MEAN                         225020      0.731746
CC_UTIL_DIFF2_MEAN                         223367      0.726371
CC_BALANCE_DIFF3_MEAN                      223307      0.726176

Top infinity features:
                            inf_count  inf_rate
SK_ID_CURR                          0       0.0
TARGET                              0       0.0
CNT_CHILDREN                        0       0.0
AMT_INCOME_TOTAL                    0       0.0
AMT_CREDIT                          0       0.0
AMT_ANNUITY                         0       0.0
AMT_GOODS_PRICE                     0       0.0
REGION_POPULATION_RELATIVE          0       0.0
DAYS_BIRTH                          0       0.0
DAYS_EMPLOYED                       0       0.0

In [11]:
inf_stats.to_csv("inf_stats.csv")
missing_stats.to_csv("missing_stats.csv")

## 3. Information Value (IV) via AutoBinning on full data — then compute df_woe

In [12]:
features = [c for c in df.columns if c not in [ID_COL, TARGET_COL, "flag_train_test"]]
y_all    = df[TARGET_COL].values

# ── Fit OptimalBinning on full data, extract IV and WoE in one pass ────────────
binners   = {}   # fitted OptimalBinning objects
woe_cols  = {}   # WoE-transformed arrays
iv_rows   = []   # IV per feature

binning_tables = {}

for col in features:
    dtype = "numerical" if pd.api.types.is_numeric_dtype(df[col]) else "categorical"
    ob = OptimalBinning(
        name=col,
        dtype=dtype,
        solver="cp",
        max_n_bins=IV_BINS
    )

    ob.fit(df[col].values, y_all)

    binners[col] = ob
    woe_cols[col] = ob.transform(df[col].values, metric="woe")

    # Lưu binning table
    bt = ob.binning_table.build()
    binning_tables[col] = bt.copy()

    try:
        iv = bt.loc[bt.index != "Totals", "IV"].sum()
    except Exception:
        iv = np.nan

    iv_rows.append({"feature": col, "iv": iv})

# ── IV table ───────────────────────────────────────────────────────────────────
iv_table = (
    pd.DataFrame(iv_rows)
    .sort_values("iv", ascending=False)
    .reset_index(drop=True)
)

bins_iv = [-np.inf, 0.01, 0.02, 0.10, 0.30, 0.50, np.inf]
labels  = ["<0.01", "0.01-0.02", "0.02-0.10", "0.10-0.30", "0.30-0.50", ">0.50"]
iv_table["group"] = pd.cut(iv_table["iv"], bins=bins_iv, labels=labels)
print(iv_table["group"].value_counts().reindex(labels).fillna(0).astype(int))

# ── Filter by IV ───────────────────────────────────────────────────────────────
keep_iv = iv_table.loc[
    iv_table["iv"].between(IV_THR, IV_MAX),
    "feature"
].tolist()
print(f"\nFeatures after IV filter: {len(keep_iv)}")

# ── Build df_woe on full data (IV-passing features only) ──────────────────────
df_woe = pd.DataFrame({col: woe_cols[col] for col in keep_iv}, index=df.index)
df_woe.insert(0, ID_COL,          df[ID_COL].values)
df_woe.insert(1, TARGET_COL,      df[TARGET_COL].values)
df_woe.insert(2, "flag_train_test", df["flag_train_test"].values)

print("df_woe shape:", df_woe.shape)
df_woe.head(3)

group
<0.01        38
0.01-0.02    49
0.02-0.10    81
0.10-0.30     3
0.30-0.50     4
>0.50         1
Name: count, dtype: int64

Features after IV filter: 138
df_woe shape: (307511, 141)

,SK_ID_CURR,TARGET,flag_train_test,EXT_SOURCE_MEAN,EXT_SOURCE_MIN,EXT_SOURCE_MAX,EXT_SOURCE_3,EXT_SOURCE_2,EMPLOY_YEARS,DAYS_EMPLOYED,...,HOUSING_LIVINGAPARTMENTS_WAS_MISSING,AMT_INCOME_TOTAL,HAS_BUREAU_HISTORY,BUREAU_HAS_BAD_DEBT,HOUSING_NONLIVINGAPARTMENTS_WAS_MISSING,HOUSING_COMMONAREA_WAS_MISSING,EXT_SOURCE_NAN_COUNT,BUREAU_DEBT_SUM,PREV_APP_COUNT,FLAG_WORK_PHONE
0,100002,1,train,-1.372552,-1.184253,-1.229897,-1.176614,-0.331357,-0.343809,-0.343809,...,0.171513,0.008517,0.047117,0.047117,0.167647,0.168085,0.109278,-0.041173,0.018093,0.053434
1,100003,0,train,-0.061017,-0.112749,0.162243,0.000000,0.396376,-0.252375,-0.252375,...,0.171513,0.146626,0.047117,0.047117,0.167647,0.168085,-0.014111,0.113854,0.018093,0.053434
2,100004,0,train,1.022666,0.786998,0.696196,0.913839,0.206619,-0.371972,-0.371972,...,-0.071716,0.036022,0.047117,0.047117,-0.066903,-0.065718,-0.014111,0.113854,0.018093,-0.193464

In [13]:
iv_table

                         feature        iv      group
0                EXT_SOURCE_MEAN  0.623410      >0.50
1                 EXT_SOURCE_MIN  0.474334  0.30-0.50
2                 EXT_SOURCE_MAX  0.451813  0.30-0.50
3                   EXT_SOURCE_3  0.335228  0.30-0.50
4                   EXT_SOURCE_2  0.320699  0.30-0.50
..                           ...       ...        ...
171  LIVE_REGION_NOT_WORK_REGION  0.000000      <0.01
172             FLAG_CONT_MOBILE  0.000000      <0.01
173            BUREAU_N_BAD_DEBT  0.000000      <0.01
174                BUREAU_N_SOLD  0.000000      <0.01
175           BUREAU_OVERDUE_SUM  0.000000      <0.01

[176 rows x 3 columns]

In [14]:
iv_table.to_csv("iv_table.csv")

In [15]:
df_woe.to_csv("df_woe_long_list.csv")

## 4. Correlation on df_woe — keep higher-IV feature in each correlated pair

In [16]:
# WoE features
woe_features = [
    c for c in df_woe.columns
    if c not in [ID_COL, TARGET_COL, "flag_train_test"]
]

# Correlation matrix
corr = df_woe[woe_features].corr().abs()
corr.to_csv("correlation_matrix.csv")

# High-correlation pairs
pairs = [
    {
        "feature_1": corr.columns[i],
        "feature_2": corr.columns[j],
        "corr": corr.iloc[i, j]
    }
    for i in range(len(corr.columns))
    for j in range(i + 1, len(corr.columns))
    if corr.iloc[i, j] > CORR_THR
]

pairs = pd.DataFrame(pairs).sort_values(
    "corr", ascending=False
).reset_index(drop=True)

pairs.to_csv("high_corr_pairs.csv", index=False)

# Drop lower-IV feature
iv_dict = iv_table.set_index("feature")["iv"].to_dict()

drop_set = set()
drop_log = []

for _, row in pairs.iterrows():
    f1, f2 = row["feature_1"], row["feature_2"]

    if f1 in drop_set or f2 in drop_set:
        continue

    iv1 = iv_dict.get(f1, 0)
    iv2 = iv_dict.get(f2, 0)

    dropped = f2 if iv1 >= iv2 else f1
    kept = f1 if dropped == f2 else f2

    drop_set.add(dropped)

    drop_log.append({
        "feature_1": f1,
        "feature_2": f2,
        "corr": row["corr"],
        "iv_1": iv1,
        "iv_2": iv2,
        "kept": kept,
        "dropped": dropped
    })

# Save drop log
pd.DataFrame(drop_log).to_csv(
    "correlation_drop_log.csv", index=False
)

# Drop features
df_woe = df_woe.drop(
    columns=[c for c in drop_set if c in df_woe.columns]
)

# Refresh IV table
surviving = [
    c for c in df_woe.columns
    if c not in [ID_COL, TARGET_COL, "flag_train_test"]
]

iv_table = (
    iv_table[iv_table["feature"].isin(surviving)]
    .sort_values("iv", ascending=False)
    .reset_index(drop=True)
)

print(f"High-corr pairs: {len(pairs)}")
print(f"Dropped by correlation: {len(drop_set)}")
print(f"Remaining features: {len(surviving)}")

High-corr pairs: 139
Dropped by correlation: 54
Remaining features: 84

## 5. VIF on df_woe — drop multicollinear features

In [17]:
import time

woe_features = [
    c for c in df_woe.columns
    if c not in [ID_COL, TARGET_COL, "flag_train_test"]
]

# df_woe columns are already numeric WoE values
X_vif = df_woe[woe_features].copy()

# Handle inf / NaN
X_vif = (
    X_vif
    .replace([np.inf, -np.inf], np.nan)
    .fillna(X_vif.median())
)

print(f"Calculating VIF for {X_vif.shape[1]} WoE features...")
t0 = time.time()

# ============================================================
# 1. Calculate VIF ONCE for all features
# ============================================================
X_tmp = sm.add_constant(X_vif, has_constant="add")

vif_vals = [
    variance_inflation_factor(X_tmp.values, i + 1)
    for i in range(len(woe_features))
]

vif_table = pd.DataFrame({
    "feature": woe_features,
    "vif": vif_vals
}).sort_values(
    "vif",
    ascending=False
).reset_index(drop=True)

print(f"Finished VIF in {time.time() - t0:.1f}s")

# ============================================================
# 2. Drop ALL features exceeding threshold — only once
# ============================================================
drop_vif = vif_table.loc[
    vif_table["vif"] > VIF_THR,
    "feature"
].tolist()

remaining = [
    c for c in woe_features
    if c not in drop_vif
]

print(f"\nVIF threshold: {VIF_THR}")
print(f"Features before VIF filter: {len(woe_features)}")
print(f"Dropped by VIF: {len(drop_vif)}")
print(f"Remaining features: {len(remaining)}")

if drop_vif:
    print("\nDropped features:")
    print(vif_table[vif_table.feature.isin(drop_vif)].to_string(index=False))

# ============================================================
# 3. Remove features from df_woe
# ============================================================
df_woe = df_woe.drop(
    columns=[c for c in drop_vif if c in df_woe.columns]
)

print("\ndf_woe shape after VIF filter:", df_woe.shape)

# ============================================================
# 4. Refresh IV table
# ============================================================
surviving = [
    c for c in df_woe.columns
    if c not in [ID_COL, TARGET_COL, "flag_train_test"]
]

iv_table = (
    iv_table[
        iv_table["feature"].isin(surviving)
    ]
    .sort_values("iv", ascending=False)
    .reset_index(drop=True)
)

print("\nIV table after VIF filter:")
print(iv_table.to_string(index=False))

Calculating VIF for 84 WoE features...
Finished VIF in 411.3s

VIF threshold: 5
Features before VIF filter: 84
Dropped by VIF: 7
Remaining features: 77

Dropped features:
                        feature       vif
                BUREAU_N_CLOSED 10.619435
      HOUSING_INFO_COMPLETENESS  5.839367
          BUREAU_CREDIT_SUM_SUM  5.792676
                 BUREAU_N_LOANS  5.741245
HOUSING_YEARS_BUILD_WAS_MISSING  5.661067
            BUREAU_ACTIVE_RATIO  5.087099
                EXT_SOURCE_MEAN  5.003347

df_woe shape after VIF filter: (307511, 80)

IV table after VIF filter:
                           feature       iv     group
                      EXT_SOURCE_3 0.335228 0.30-0.50
                      EXT_SOURCE_2 0.320699 0.30-0.50
                      EMPLOY_YEARS 0.114054 0.10-0.30
          BUREAU_DEBT_CREDIT_RATIO 0.103937 0.10-0.30
                   AMT_GOODS_PRICE 0.092037 0.02-0.10
                               AGE 0.086928 0.02-0.10
            BUREAU_DAYS_CREDIT_MAX 0.082983 0.02-0.10
            BUREAU_DAYS_CREDIT_MIN 0.079678 0.02-0.10
                GOODS_CREDIT_RATIO 0.076063 0.02-0.10
PREV_CREDIT_APPLICATION_RATIO_MEAN 0.072437 0.02-0.10
                 PREV_REFUSAL_RATE 0.069869 0.02-0.10
                PREV_APPROVAL_RATE 0.064407 0.02-0.10
                     INST_PCT_LATE 0.063627 0.02-0.10
                        AMT_CREDIT 0.059368 0.02-0.10
         ORGANIZATION_TYPE_GROUPED 0.058196 0.02-0.10
                  NAME_INCOME_TYPE 0.057869 0.02-0.10
           INST_PAYMENT_RATIO_MEAN 0.054195 0.02-0.10
       REGION_RATING_CLIENT_W_CITY 0.051201 0.02-0.10
               NAME_EDUCATION_TYPE 0.049654 0.02-0.10
           LAST_PHONE_CHANGE_YEARS 0.047855 0.02-0.10
     BUREAU_DAYS_CREDIT_UPDATE_MAX 0.047808 0.02-0.10
            PREV_DAYS_DECISION_MIN 0.044539 0.02-0.10
                   DAYS_ID_PUBLISH 0.040253 0.02-0.10
                    EXT_SOURCE_STD 0.037342 0.02-0.10
        REGION_POPULATION_RELATIVE 0.035649 0.02-0.10
            ORGANIZATION_TYPE_FREQ 0.034930 0.02-0.10
              POS_PAID_LAST_2M_SUM 0.032367 0.02-0.10
            REG_CITY_NOT_WORK_CITY 0.032207 0.02-0.10
                 HOUSING_TOTALAREA 0.031676 0.02-0.10
                       AMT_ANNUITY 0.031179 0.02-0.10
              POS_PAID_LAST_1M_SUM 0.030094 0.02-0.10
             POS_PAID_LAST_2M_MEAN 0.029853 0.02-0.10
   HOUSING_YEARS_BEGINEXPLUATATION 0.029216 0.02-0.10
                       CREDIT_TERM 0.028996 0.02-0.10
                REGISTRATION_YEARS 0.028487 0.02-0.10
                 HOUSING_FLOORSMAX 0.028373 0.02-0.10
               INST_N_PAYMENTS_90D 0.028082 0.02-0.10
             POS_PAID_LAST_1M_MEAN 0.027211 0.02-0.10
            BUREAU_CREDIT_SUM_MEAN 0.025698 0.02-0.10
             PREV_CNT_PAYMENT_MEAN 0.025618 0.02-0.10
                   BUREAU_N_ACTIVE 0.025490 0.02-0.10
                       POS_N_LOANS 0.023262 0.02-0.10
              POS_PAID_LAST_6M_SUM 0.022316 0.02-0.10
            REG_CITY_NOT_LIVE_CITY 0.022299 0.02-0.10
                  HOUSING_LANDAREA 0.022276 0.02-0.10
               HOUSING_YEARS_BUILD 0.021774 0.02-0.10
                NAME_FAMILY_STATUS 0.021702 0.02-0.10
              HOUSING_BASEMENTAREA 0.021414 0.02-0.10
               CC_DRAWINGS_ATM_SUM 0.020165 0.02-0.10
                      POS_DPD_MEAN 0.019478 0.01-0.02
         PREV_AMT_APPLICATION_MEAN 0.018743 0.01-0.02
       INST_DAYS_ENTRY_PAYMENT_MAX 0.018663 0.01-0.02
        AMT_REQ_CREDIT_BUREAU_YEAR 0.018093 0.01-0.02
                 HOUSING_ENTRANCES 0.017504 0.01-0.02
             POS_PAID_LAST_6M_MEAN 0.017475 0.01-0.02
         AMT_REQ_CREDIT_BUREAU_QRT 0.016871 0.01-0.02
               INST_N_PAYMENTS_30D 0.016829 0.01-0.02
  POS_INSTALMENT_FUTURE_TREND_MEAN 0.015962 0.01-0.02
                 NAME_HOUSING_TYPE 0.015055 0.01-0.02
                NAME_CONTRACT_TYPE 0.015039 0.01-0.02
              INST_N_PAYMENTS_365D 0.014976 0.01-0.02
                 HOUSING_FLOORSMIN 0.014438 0.01-0.02
                   INST_N_PAYMENTS 0.014437 0.01-0.02
          HOUSING_LIVINGAPARTMENTS 0.014120 0.01-0.02
                POS_DPD_TREND_MEAN 0.014074 0.01-0.02
          DEF_30_CNT_SOCIAL_CIRCLE 0.014018 0.01-0.02
            PREV_DAYS_DECISION_MAX 0.013893 0.01-0.02
         AMT_REQ_CREDIT_BUREAU_MON 0.013665 0.01-0.02
               CREDIT_INCOME_RATIO 0.012657 0.01-0.02
                HOUSING_COMMONAREA 0.012626 0.01-0.02
          INST_AMT_PAYMENT_SUM_60D 0.012467 0.01-0.02
          INST_AMT_PAYMENT_SUM_30D 0.012447 0.01-0.02
                  AMT_INCOME_TOTAL 0.011868 0.01-0.02
              EXT_SOURCE_NAN_COUNT 0.010887 0.01-0.02
                   BUREAU_DEBT_SUM 0.010824 0.01-0.02
                    PREV_APP_COUNT 0.010450 0.01-0.02
                   FLAG_WORK_PHONE 0.010329 0.01-0.02

In [18]:
vif_table.to_csv("vif_table.csv")

## 6. Save feature shortlist before stepwise

In [19]:
shortlist_features = [c for c in df_woe.columns if c not in [ID_COL, TARGET_COL, "flag_train_test"]]

shortlist_df = (
    iv_table[iv_table.feature.isin(shortlist_features)]
    [["feature", "iv", "group"]]
    .sort_values("iv", ascending=False)
    .reset_index(drop=True)
)
shortlist_df.to_csv(FEATURE_SHORTLIST, index=False)

print(f"Feature shortlist saved to: {FEATURE_SHORTLIST}")
print(f"Total features in shortlist: {len(shortlist_features)}")
print(shortlist_df.to_string(index=False))

Feature shortlist saved to: feature_shortlist.csv
Total features in shortlist: 77
                           feature       iv     group
                      EXT_SOURCE_3 0.335228 0.30-0.50
                      EXT_SOURCE_2 0.320699 0.30-0.50
                      EMPLOY_YEARS 0.114054 0.10-0.30
          BUREAU_DEBT_CREDIT_RATIO 0.103937 0.10-0.30
                   AMT_GOODS_PRICE 0.092037 0.02-0.10
                               AGE 0.086928 0.02-0.10
            BUREAU_DAYS_CREDIT_MAX 0.082983 0.02-0.10
            BUREAU_DAYS_CREDIT_MIN 0.079678 0.02-0.10
                GOODS_CREDIT_RATIO 0.076063 0.02-0.10
PREV_CREDIT_APPLICATION_RATIO_MEAN 0.072437 0.02-0.10
                 PREV_REFUSAL_RATE 0.069869 0.02-0.10
                PREV_APPROVAL_RATE 0.064407 0.02-0.10
                     INST_PCT_LATE 0.063627 0.02-0.10
                        AMT_CREDIT 0.059368 0.02-0.10
         ORGANIZATION_TYPE_GROUPED 0.058196 0.02-0.10
                  NAME_INCOME_TYPE 0.057869 0.02-0.10
           INST_PAYMENT_RATIO_MEAN 0.054195 0.02-0.10
       REGION_RATING_CLIENT_W_CITY 0.051201 0.02-0.10
               NAME_EDUCATION_TYPE 0.049654 0.02-0.10
           LAST_PHONE_CHANGE_YEARS 0.047855 0.02-0.10
     BUREAU_DAYS_CREDIT_UPDATE_MAX 0.047808 0.02-0.10
            PREV_DAYS_DECISION_MIN 0.044539 0.02-0.10
                   DAYS_ID_PUBLISH 0.040253 0.02-0.10
                    EXT_SOURCE_STD 0.037342 0.02-0.10
        REGION_POPULATION_RELATIVE 0.035649 0.02-0.10
            ORGANIZATION_TYPE_FREQ 0.034930 0.02-0.10
              POS_PAID_LAST_2M_SUM 0.032367 0.02-0.10
            REG_CITY_NOT_WORK_CITY 0.032207 0.02-0.10
                 HOUSING_TOTALAREA 0.031676 0.02-0.10
                       AMT_ANNUITY 0.031179 0.02-0.10
              POS_PAID_LAST_1M_SUM 0.030094 0.02-0.10
             POS_PAID_LAST_2M_MEAN 0.029853 0.02-0.10
   HOUSING_YEARS_BEGINEXPLUATATION 0.029216 0.02-0.10
                       CREDIT_TERM 0.028996 0.02-0.10
                REGISTRATION_YEARS 0.028487 0.02-0.10
                 HOUSING_FLOORSMAX 0.028373 0.02-0.10
               INST_N_PAYMENTS_90D 0.028082 0.02-0.10
             POS_PAID_LAST_1M_MEAN 0.027211 0.02-0.10
            BUREAU_CREDIT_SUM_MEAN 0.025698 0.02-0.10
             PREV_CNT_PAYMENT_MEAN 0.025618 0.02-0.10
                   BUREAU_N_ACTIVE 0.025490 0.02-0.10
                       POS_N_LOANS 0.023262 0.02-0.10
              POS_PAID_LAST_6M_SUM 0.022316 0.02-0.10
            REG_CITY_NOT_LIVE_CITY 0.022299 0.02-0.10
                  HOUSING_LANDAREA 0.022276 0.02-0.10
               HOUSING_YEARS_BUILD 0.021774 0.02-0.10
                NAME_FAMILY_STATUS 0.021702 0.02-0.10
              HOUSING_BASEMENTAREA 0.021414 0.02-0.10
               CC_DRAWINGS_ATM_SUM 0.020165 0.02-0.10
                      POS_DPD_MEAN 0.019478 0.01-0.02
         PREV_AMT_APPLICATION_MEAN 0.018743 0.01-0.02
       INST_DAYS_ENTRY_PAYMENT_MAX 0.018663 0.01-0.02
        AMT_REQ_CREDIT_BUREAU_YEAR 0.018093 0.01-0.02
                 HOUSING_ENTRANCES 0.017504 0.01-0.02
             POS_PAID_LAST_6M_MEAN 0.017475 0.01-0.02
         AMT_REQ_CREDIT_BUREAU_QRT 0.016871 0.01-0.02
               INST_N_PAYMENTS_30D 0.016829 0.01-0.02
  POS_INSTALMENT_FUTURE_TREND_MEAN 0.015962 0.01-0.02
                 NAME_HOUSING_TYPE 0.015055 0.01-0.02
                NAME_CONTRACT_TYPE 0.015039 0.01-0.02
              INST_N_PAYMENTS_365D 0.014976 0.01-0.02
                 HOUSING_FLOORSMIN 0.014438 0.01-0.02
                   INST_N_PAYMENTS 0.014437 0.01-0.02
          HOUSING_LIVINGAPARTMENTS 0.014120 0.01-0.02
                POS_DPD_TREND_MEAN 0.014074 0.01-0.02
          DEF_30_CNT_SOCIAL_CIRCLE 0.014018 0.01-0.02
            PREV_DAYS_DECISION_MAX 0.013893 0.01-0.02
         AMT_REQ_CREDIT_BUREAU_MON 0.013665 0.01-0.02
               CREDIT_INCOME_RATIO 0.012657 0.01-0.02
                HOUSING_COMMONAREA 0.012626 0.01-0.02
          INST_AMT_PAYMENT_SUM_60D 0.012467 0.01-0.02
          INST_AMT_PAYMENT_SUM_30D 0.012447 0.01-0.02
                  AMT_INCOME_TOTAL 0.011868 0.01-0.02
              EXT_SOURCE_NAN_COUNT 0.010887 0.01-0.02
                   BUREAU_DEBT_SUM 0.010824 0.01-0.02
                    PREV_APP_COUNT 0.010450 0.01-0.02
                   FLAG_WORK_PHONE 0.010329 0.01-0.02

## 7. Train / Test split from df_woe

In [20]:
train_woe = df_woe[df_woe["flag_train_test"] == "train"].reset_index(drop=True)
test_woe  = df_woe[df_woe["flag_train_test"] == "test"].reset_index(drop=True)

model_features = [c for c in df_woe.columns if c not in [ID_COL, TARGET_COL, "flag_train_test"]]

X_train = train_woe[model_features]
y_train = train_woe[TARGET_COL]
X_test  = test_woe[model_features]
y_test  = test_woe[TARGET_COL]

print(f"Train: {train_woe.shape}  |  Test: {test_woe.shape}")

Train: (215257, 80)  |  Test: (92254, 80)

## 8. Stepwise Logistic Regression (forward, Gini-based)

In [21]:
from numpy.linalg import matrix_rank

def fit_logit(X, y):
    X = X.replace([np.inf, -np.inf], np.nan)
    if X.isna().any().any():
        raise ValueError("X contains NaN.")
    X_c = sm.add_constant(X, has_constant="add")
    if matrix_rank(X_c) < X_c.shape[1]:
        return None
    return sm.Logit(y, X_c).fit(disp=False, method="newton")


def gini(y_true, y_score):
    return 2 * roc_auc_score(y_true, y_score) - 1


# Use shortlist order (sorted by IV) as candidates
candidates   = [f for f in shortlist_df["feature"].tolist() if f in X_train.columns]
selected     = []
current_gini = 0.0
log_rows     = []

for i, feat in enumerate(candidates, 1):
    print(f"[{i}/{len(candidates)}] Testing: {feat}", flush=True)

    trial_feats = selected + [feat]
    model_try   = fit_logit(X_train[trial_feats], y_train)

    if model_try is None:
        print("    -> skipped (singular matrix)", flush=True)
        log_rows.append({"feature": feat, "gini_train": None,
                         "improvement": None, "accepted": False, "note": "singular"})
        continue

    prob_train  = model_try.predict(sm.add_constant(X_train[trial_feats], has_constant="add"))
    new_gini    = gini(y_train, prob_train)
    improvement = new_gini - current_gini
    accept      = improvement >= GINI_IMPROVE_THR

    print(f"    Gini={new_gini:.4f}  Improve={improvement:.4f}  {'ACCEPT' if accept else 'REJECT'}",
          flush=True)

    log_rows.append({"feature": feat, "gini_train": round(new_gini, 4),
                     "improvement": round(improvement, 4), "accepted": accept, "note": ""})

    if accept:
        selected     = trial_feats
        current_gini = new_gini

step_log = pd.DataFrame(log_rows)
print(step_log.to_string(index=False))
print(f"\nFinal model features ({len(selected)}): {selected}")

[1/77] Testing: EXT_SOURCE_3
    Gini=0.3154  Improve=0.3154  ACCEPT
[2/77] Testing: EXT_SOURCE_2
    Gini=0.4221  Improve=0.1067  ACCEPT
[3/77] Testing: EMPLOY_YEARS
    Gini=0.4351  Improve=0.0131  ACCEPT
[4/77] Testing: BUREAU_DEBT_CREDIT_RATIO
    Gini=0.4403  Improve=0.0052  ACCEPT
[5/77] Testing: AMT_GOODS_PRICE
    Gini=0.4517  Improve=0.0114  ACCEPT
[6/77] Testing: AGE
    Gini=0.4543  Improve=0.0026  REJECT
[7/77] Testing: BUREAU_DAYS_CREDIT_MAX
    Gini=0.4518  Improve=0.0001  REJECT
[8/77] Testing: BUREAU_DAYS_CREDIT_MIN
    Gini=0.4517  Improve=0.0001  REJECT
[9/77] Testing: GOODS_CREDIT_RATIO
    Gini=0.4606  Improve=0.0089  ACCEPT
[10/77] Testing: PREV_CREDIT_APPLICATION_RATIO_MEAN
    Gini=0.4692  Improve=0.0086  ACCEPT
[11/77] Testing: PREV_REFUSAL_RATE
    Gini=0.4732  Improve=0.0040  REJECT
[12/77] Testing: PREV_APPROVAL_RATE
    Gini=0.4716  Improve=0.0025  REJECT
[13/77] Testing: INST_PCT_LATE
    Gini=0.4785  Improve=0.0094  ACCEPT
[14/77] Testing: AMT_CREDIT
    Gini=0.4790  Improve=0.0005  REJECT
[15/77] Testing: ORGANIZATION_TYPE_GROUPED
    Gini=0.4851  Improve=0.0066  ACCEPT
[16/77] Testing: NAME_INCOME_TYPE
    Gini=0.4857  Improve=0.0006  REJECT
[17/77] Testing: INST_PAYMENT_RATIO_MEAN
    Gini=0.4857  Improve=0.0005  REJECT
[18/77] Testing: REGION_RATING_CLIENT_W_CITY
    Gini=0.4865  Improve=0.0013  REJECT
[19/77] Testing: NAME_EDUCATION_TYPE
    Gini=0.4902  Improve=0.0051  ACCEPT
[20/77] Testing: LAST_PHONE_CHANGE_YEARS
    Gini=0.4910  Improve=0.0008  REJECT
[21/77] Testing: BUREAU_DAYS_CREDIT_UPDATE_MAX
    Gini=0.4902  Improve=0.0000  REJECT
[22/77] Testing: PREV_DAYS_DECISION_MIN
    Gini=0.4919  Improve=0.0017  REJECT
[23/77] Testing: DAYS_ID_PUBLISH
    Gini=0.4909  Improve=0.0007  REJECT
[24/77] Testing: EXT_SOURCE_STD
    Gini=0.4910  Improve=0.0008  REJECT
[25/77] Testing: REGION_POPULATION_RELATIVE
    Gini=0.4906  Improve=0.0004  REJECT
[26/77] Testing: ORGANIZATION_TYPE_FREQ
    Gini=0.4902  Improve=0.0000  REJECT
[27/77] Testing: POS_PAID_LAST_2M_SUM
    Gini=0.4947  Improve=0.0045  REJECT
[28/77] Testing: REG_CITY_NOT_WORK_CITY
    Gini=0.4907  Improve=0.0005  REJECT
[29/77] Testing: HOUSING_TOTALAREA
    Gini=0.4911  Improve=0.0009  REJECT
[30/77] Testing: AMT_ANNUITY
    Gini=0.4905  Improve=0.0003  REJECT
[31/77] Testing: POS_PAID_LAST_1M_SUM
    Gini=0.4939  Improve=0.0037  REJECT
[32/77] Testing: POS_PAID_LAST_2M_MEAN
    Gini=0.4946  Improve=0.0044  REJECT
[33/77] Testing: HOUSING_YEARS_BEGINEXPLUATATION
    Gini=0.4911  Improve=0.0009  REJECT
[34/77] Testing: CREDIT_TERM
    Gini=0.4927  Improve=0.0025  REJECT
[35/77] Testing: REGISTRATION_YEARS
    Gini=0.4911  Improve=0.0009  REJECT
[36/77] Testing: HOUSING_FLOORSMAX
    Gini=0.4912  Improve=0.0009  REJECT
[37/77] Testing: INST_N_PAYMENTS_90D
    Gini=0.4930  Improve=0.0028  REJECT
[38/77] Testing: POS_PAID_LAST_1M_MEAN
    Gini=0.4938  Improve=0.0036  REJECT
[39/77] Testing: BUREAU_CREDIT_SUM_MEAN
    Gini=0.4915  Improve=0.0013  REJECT
[40/77] Testing: PREV_CNT_PAYMENT_MEAN
    Gini=0.4932  Improve=0.0030  REJECT
[41/77] Testing: BUREAU_N_ACTIVE
    Gini=0.4912  Improve=0.0009  REJECT
[42/77] Testing: POS_N_LOANS
    Gini=0.4929  Improve=0.0026  REJECT
[43/77] Testing: POS_PAID_LAST_6M_SUM
    Gini=0.4942  Improve=0.0040  REJECT
[44/77] Testing: REG_CITY_NOT_LIVE_CITY
    Gini=0.4913  Improve=0.0011  REJECT
[45/77] Testing: HOUSING_LANDAREA
    Gini=0.4908  Improve=0.0006  REJECT
[46/77] Testing: HOUSING_YEARS_BUILD
    Gini=0.4911  Improve=0.0009  REJECT
[47/77] Testing: NAME_FAMILY_STATUS
    Gini=0.4909  Improve=0.0007  REJECT
[48/77] Testing: HOUSING_BASEMENTAREA
    Gini=0.4910  Improve=0.0008  REJECT
[49/77] Testing: CC_DRAWINGS_ATM_SUM
    Gini=0.4928  Improve=0.0025  REJECT
[50/77] Testing: POS_DPD_MEAN
    Gini=0.4903  Improve=0.0001  REJECT
[51/77] Testing: PREV_AMT_APPLICATION_MEAN
    Gini=0.4913  Improve=0.0011  REJECT
[52/77] Testing: INST_DAYS_ENTRY_PAYMENT_MAX
    Gini=0.4921  Improve=0.0018  REJECT
[53/77] Testing: AMT_REQ_CREDIT_BUREAU_YEAR
    Gini=0.4902  Improve=0.0000  REJECT
[54/77] Testing: HOUSING_ENTRANCES
    Gini=0.4908  Improve=0.0005  REJECT
[55/77] Testing: POS_PAID_LAST_6M_MEAN
    Gini=0.4931  Improve=0.0029  REJECT
[56/77] Testing: AMT_REQ_CREDIT_BUREAU_QRT
    Gini=0.4909  Improve=0.0007  REJECT
[57/77] Testing: INST_N_PAYMENTS_30D
    Gini=0.4918  Improve=0.0016  REJECT
[58/77] Testing: POS_INSTALMENT_FUTURE_TREND_MEAN
    Gini=0.4930  Improve=0.0028  REJECT
[59/77] Testing: NAME_HOUSING_TYPE
    Gini=0.4904  Improve=0.0002  REJECT
[60/77] Testing: NAME_CONTRACT_TYPE
    Gini=0.4918  Improve=0.0016  REJECT
[61/77] Testing: INST_N_PAYMENTS_365D
    Gini=0.4915  Improve=0.0012  REJECT
[62/77] Testing: HOUSING_FLOORSMIN
    Gini=0.4907  Improve=0.0005  REJECT
[63/77] Testing: INST_N_PAYMENTS
    Gini=0.4915  Improve=0.0013  REJECT
[64/77] Testing: HOUSING_LIVINGAPARTMENTS
    Gini=0.4908  Improve=0.0005  REJECT
[65/77] Testing: POS_DPD_TREND_MEAN
    Gini=0.4904  Improve=0.0002  REJECT
[66/77] Testing: DEF_30_CNT_SOCIAL_CIRCLE
    Gini=0.4917  Improve=0.0015  REJECT
[67/77] Testing: PREV_DAYS_DECISION_MAX
    Gini=0.4903  Improve=0.0001  REJECT
[68/77] Testing: AMT_REQ_CREDIT_BUREAU_MON
    Gini=0.4906  Improve=0.0003  REJECT
[69/77] Testing: CREDIT_INCOME_RATIO
    Gini=0.4903  Improve=0.0001  REJECT
[70/77] Testing: HOUSING_COMMONAREA
    Gini=0.4909  Improve=0.0007  REJECT
[71/77] Testing: INST_AMT_PAYMENT_SUM_60D
    Gini=0.4907  Improve=0.0005  REJECT
[72/77] Testing: INST_AMT_PAYMENT_SUM_30D
    Gini=0.4908  Improve=0.0006  REJECT
[73/77] Testing: AMT_INCOME_TOTAL
    Gini=0.4902  Improve=-0.0000  REJECT
[74/77] Testing: EXT_SOURCE_NAN_COUNT
    Gini=0.4911  Improve=0.0008  REJECT
[75/77] Testing: BUREAU_DEBT_SUM
    Gini=0.4906  Improve=0.0004  REJECT
[76/77] Testing: PREV_APP_COUNT
    Gini=0.4905  Improve=0.0003  REJECT
[77/77] Testing: FLAG_WORK_PHONE
    Gini=0.4909  Improve=0.0007  REJECT
                           feature  gini_train  improvement  accepted note
                      EXT_SOURCE_3      0.3154       0.3154      True
                      EXT_SOURCE_2      0.4221       0.1067      True
                      EMPLOY_YEARS      0.4351       0.0131      True
          BUREAU_DEBT_CREDIT_RATIO      0.4403       0.0052      True
                   AMT_GOODS_PRICE      0.4517       0.0114      True
                               AGE      0.4543       0.0026     False
            BUREAU_DAYS_CREDIT_MAX      0.4518       0.0001     False
            BUREAU_DAYS_CREDIT_MIN      0.4517       0.0001     False
                GOODS_CREDIT_RATIO      0.4606       0.0089      True
PREV_CREDIT_APPLICATION_RATIO_MEAN      0.4692       0.0086      True
                 PREV_REFUSAL_RATE      0.4732       0.0040     False
                PREV_APPROVAL_RATE      0.4716       0.0025     False
                     INST_PCT_LATE      0.4785       0.0094      True
                        AMT_CREDIT      0.4790       0.0005     False
         ORGANIZATION_TYPE_GROUPED      0.4851       0.0066      True
                  NAME_INCOME_TYPE      0.4857       0.0006     False
           INST_PAYMENT_RATIO_MEAN      0.4857       0.0005     False
       REGION_RATING_CLIENT_W_CITY      0.4865       0.0013     False
               NAME_EDUCATION_TYPE      0.4902       0.0051      True
           LAST_PHONE_CHANGE_YEARS      0.4910       0.0008     False
     BUREAU_DAYS_CREDIT_UPDATE_MAX      0.4902       0.0000     False
            PREV_DAYS_DECISION_MIN      0.4919       0.0017     False
                   DAYS_ID_PUBLISH      0.4909       0.0007     False
                    EXT_SOURCE_STD      0.4910       0.0008     False
        REGION_POPULATION_RELATIVE      0.4906       0.0004     False
            ORGANIZATION_TYPE_FREQ      0.4902       0.0000     False
              POS_PAID_LAST_2M_SUM      0.4947       0.0045     False
            REG_CITY_NOT_WORK_CITY      0.4907       0.0005     False
                 HOUSING_TOTALAREA      0.4911       0.0009     False
                       AMT_ANNUITY      0.4905       0.0003     False
              POS_PAID_LAST_1M_SUM      0.4939       0.0037     False
             POS_PAID_LAST_2M_MEAN      0.4946       0.0044     False
   HOUSING_YEARS_BEGINEXPLUATATION      0.4911       0.0009     False
                       CREDIT_TERM      0.4927       0.0025     False
                REGISTRATION_YEARS      0.4911       0.0009     False
                 HOUSING_FLOORSMAX      0.4912       0.0009     False
               INST_N_PAYMENTS_90D      0.4930       0.0028     False
             POS_PAID_LAST_1M_MEAN      0.4938       0.0036     False
            BUREAU_CREDIT_SUM_MEAN      0.4915       0.0013     False
             PREV_CNT_PAYMENT_MEAN      0.4932       0.0030     False
                   BUREAU_N_ACTIVE      0.4912       0.0009     False
                       POS_N_LOANS      0.4929       0.0026     False
              POS_PAID_LAST_6M_SUM      0.4942       0.0040     False
            REG_CITY_NOT_LIVE_CITY      0.4913       0.0011     False
                  HOUSING_LANDAREA      0.4908       0.0006     False
               HOUSING_YEARS_BUILD      0.4911       0.0009     False
                NAME_FAMILY_STATUS      0.4909       0.0007     False
              HOUSING_BASEMENTAREA      0.4910       0.0008     False
               CC_DRAWINGS_ATM_SUM      0.4928       0.0025     False
                      POS_DPD_MEAN      0.4903       0.0001     False
         PREV_AMT_APPLICATION_MEAN      0.4913       0.0011     False
       INST_DAYS_ENTRY_PAYMENT_MAX      0.4921       0.0018     False
        AMT_REQ_CREDIT_BUREAU_YEAR      0.4902       0.0000     False
                 HOUSING_ENTRANCES      0.4908       0.0005     False
             POS_PAID_LAST_6M_MEAN      0.4931       0.0029     False
         AMT_REQ_CREDIT_BUREAU_QRT      0.4909       0.0007     False
               INST_N_PAYMENTS_30D      0.4918       0.0016     False
  POS_INSTALMENT_FUTURE_TREND_MEAN      0.4930       0.0028     False
                 NAME_HOUSING_TYPE      0.4904       0.0002     False
                NAME_CONTRACT_TYPE      0.4918       0.0016     False
              INST_N_PAYMENTS_365D      0.4915       0.0012     False
                 HOUSING_FLOORSMIN      0.4907       0.0005     False
                   INST_N_PAYMENTS      0.4915       0.0013     False
          HOUSING_LIVINGAPARTMENTS      0.4908       0.0005     False
                POS_DPD_TREND_MEAN      0.4904       0.0002     False
          DEF_30_CNT_SOCIAL_CIRCLE      0.4917       0.0015     False
            PREV_DAYS_DECISION_MAX      0.4903       0.0001     False
         AMT_REQ_CREDIT_BUREAU_MON      0.4906       0.0003     False
               CREDIT_INCOME_RATIO      0.4903       0.0001     False
                HOUSING_COMMONAREA      0.4909       0.0007     False
          INST_AMT_PAYMENT_SUM_60D      0.4907       0.0005     False
          INST_AMT_PAYMENT_SUM_30D      0.4908       0.0006     False
                  AMT_INCOME_TOTAL      0.4902      -0.0000     False
              EXT_SOURCE_NAN_COUNT      0.4911       0.0008     False
                   BUREAU_DEBT_SUM      0.4906       0.0004     False
                    PREV_APP_COUNT      0.4905       0.0003     False
                   FLAG_WORK_PHONE      0.4909       0.0007     False

Final model features (10): ['EXT_SOURCE_3', 'EXT_SOURCE_2', 'EMPLOY_YEARS', 'BUREAU_DEBT_CREDIT_RATIO', 'AMT_GOODS_PRICE', 'GOODS_CREDIT_RATIO', 'PREV_CREDIT_APPLICATION_RATIO_MEAN', 'INST_PCT_LATE', 'ORGANIZATION_TYPE_GROUPED', 'NAME_EDUCATION_TYPE']

## 9. Final model & Test Gini

In [22]:
final_model = fit_logit(X_train[selected], y_train)
print(final_model.summary())

prob_train_final = final_model.predict(sm.add_constant(X_train[selected]))
prob_test_final  = final_model.predict(sm.add_constant(X_test[selected]))

gini_train = gini(y_train, prob_train_final)
gini_test  = gini(y_test,  prob_test_final)

print(f"\nGini Train : {gini_train:.4f}")
print(f"Gini Test  : {gini_test:.4f}")

                           Logit Regression Results
==============================================================================
Dep. Variable:                 TARGET   No. Observations:               215257
Model:                          Logit   Df Residuals:                   215246
Method:                           MLE   Df Model:                           10
Date:                Sun, 16 Aug 2026   Pseudo R-squ.:                  0.1081
Time:                        23:06:15   Log-Likelihood:                -53861.
converged:                       True   LL-Null:                       -60388.
Covariance Type:            nonrobust   LLR p-value:                     0.000
======================================================================================================
                                         coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
const                                 -2.4487      0.009   -268.086      0.000      -2.467      -2.431
EXT_SOURCE_3                          -0.7352      0.015    -49.331      0.000      -0.764      -0.706
EXT_SOURCE_2                          -0.8217      0.015    -56.134      0.000      -0.850      -0.793
EMPLOY_YEARS                          -0.5753      0.031    -18.737      0.000      -0.635      -0.515
BUREAU_DEBT_CREDIT_RATIO              -0.4271      0.028    -15.472      0.000      -0.481      -0.373
AMT_GOODS_PRICE                       -0.5081      0.028    -18.022      0.000      -0.563      -0.453
GOODS_CREDIT_RATIO                    -0.5694      0.029    -19.373      0.000      -0.627      -0.512
PREV_CREDIT_APPLICATION_RATIO_MEAN    -0.6016      0.031    -19.146      0.000      -0.663      -0.540
INST_PCT_LATE                         -0.7142      0.033    -21.609      0.000      -0.779      -0.649
ORGANIZATION_TYPE_GROUPED             -0.6801      0.036    -18.928      0.000      -0.751      -0.610
NAME_EDUCATION_TYPE                   -0.6639      0.040    -16.648      0.000      -0.742      -0.586
======================================================================================================

Gini Train : 0.4902
Gini Test  : 0.4919

In [23]:
import pickle

with open("binning_tables.pkl", "wb") as f:
    pickle.dump(binning_tables, f)
with open("binners.pkl", "wb") as f:
    pickle.dump(binners, f)
with open("model.pkl", "wb") as f:
    pickle.dump(final_model, f)